site_name: REBOUND
nav:
  - Home: 
    - index.md
    - quickstart.md
    - install.md
    - acknowledgements.md
  - 'C Documentation':
    - c_installation.md
    - c_compile.md
    - c_compile_errors.md
    - c_simpleexample.md
    - 'Structures':
      - c_simulationstructure.md
      - c_structures.md
      - c_integratorstructures.md
    - 'Functions':
      - c_collisionresolvefunctions.md
      - c_switchingfunctions.md
      - c_randomsamplingfunctions.md
      - c_outputfunctions.md
  - pythonapi.md
  - Examples: examples.md
theme:
  name: material
  logo: img/rebound.png
  favicon: img/favicon.ico
  features:
    - navigation.tabs
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js      
