site_name: REBOUND
nav:
  - "Home": index.md
  - "Getting started":
    - quickstart.md
    - c_compile.md
    - c_simulationstructure.md
    - c_simpleexample.md
  - "Modules":
    - modules.md
    - integrators.md
    - c_integratorstructures.md
    - c_switchingfunctions.md
    - collisiondetection.md
    - c_collisionresolvefunctions.md
    - boundaryconditions.md
    - gravity.md
  - 'Concepts':
    - 'Orbits':
      - None
    - c_structures.md
    - c_randomsamplingfunctions.md
    - c_outputfunctions.md
  - Examples: examples.md
theme:
  name: material
  logo: img/rebound.png
  favicon: img/favicon.ico
  features:
    - navigation.tabs
markdown_extensions:
  - admonition
  - def_list
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js      
